insert into PRODUCTS (product_id, title, price) values (1, 'Cornish Hen', 5.5);
insert into PRODUCTS (product_id, title, price) values (2, 'Irish Cream', 94.5);
insert into PRODUCTS (product_id, title, price) values (3, 'Ocean Spray', 77.7);
insert into PRODUCTS (product_id, title, price) values (4, 'Bamboo Shoots', 93.1);
insert into PRODUCTS (product_id, title, price) values (5, 'Foam Tray', 21.7);
insert into PRODUCTS (product_id, title, price) values (6, 'Olive', 45.1);
insert into PRODUCTS (product_id, title, price) values (7, 'Wine', 66.3);
insert into PRODUCTS (product_id, title, price) values (8, 'Bulgar', 39.5);
insert into PRODUCTS (product_id, title, price) values (9, 'Bouillion', 81.4);
insert into PRODUCTS (product_id, title, price) values (10, 'Energy Drink', 52.1);

insert into BASKETS(basket_id) values(1)
insert into BASKETS(basket_id) values(2)

insert into USERS (user_id, username, password, USER_ROLE, basket_id) values (1, 'iharstasenka@tut.by', '$2a$12$vXvHf5yDwn8Eo8PmqxQ7YuSF56wmpcndBeigQVNPEYwYlD4e0SZ86', 0, 1);
insert into USERS (user_id, username, password, USER_ROLE, basket_id) values (2, 'johndoe125@gmail.com', '$2a$12$vXvHf5yDwn8Eo8PmqxQ7YuSF56wmpcndBeigQVNPEYwYlD4e0SZ86', 1, 2);

